// Single source of truth for the E2E harness: shared constants + the environment
// prep, in one plain-ESM module so both the TypeScript side (playwright.config.ts,
// specs, helpers) and the server command can use it.
//
// Playwright starts the `webServer` BEFORE globalSetup, so the app must be ready
// the moment serve boots. We therefore prepare the environment IN the server
// command (`node tests/e2e/prepare.mjs && php artisan serve …`): importing this
// file only reads the constants; running it as `node …/prepare.mjs` also executes
// prepare() — writing `.env.e2e`, recreating the SQLite DB, migrating, and
// provisioning the owner — before serve ever binds the port.
//
// Everything is FULLY ISOLATED from your dev stack: a throwaway SQLite file and a
// generated `.env.e2e` (selected with APP_ENV=e2e). Dev uses MySQL (see .env) —
// nothing here touches it, so the suite can migrate:fresh with impunity.
import { execFileSync } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

const root = process.cwd();

// A dedicated loopback port so E2E never collides with `composer dev` (:8000).
export const E2E_PORT = 8100;
export const BASE_URL = `http://127.0.0.1:${E2E_PORT}`;

// APP_ENV=e2e makes Laravel load `.env.e2e`; it's on `artisan serve`'s passthrough
// list, so the built-in PHP server inherits it and each request boots that config.
export const APP_ENV = 'e2e';

// Throwaway artifacts (both gitignored). Absolute paths remove all ambiguity.
export const E2E_DATABASE = path.join(root, 'database', 'e2e.sqlite');
export const E2E_ENV_FILE = path.join(root, '.env.e2e');

// The single owner account the suite logs in as — created below via the real
// app:create-user command, exactly how a self-hoster provisions the owner.
export const OWNER = {
    name: 'E2E Owner',
    email: 'owner@e2e.test',
    password: 'e2e-password',
};

// Child processes inherit APP_ENV=e2e so artisan loads `.env.e2e` (not `.env`).
const childEnv = { ...process.env, APP_ENV };

function artisan(args) {
    execFileSync('php', ['artisan', ...args], { cwd: root, env: childEnv, stdio: 'inherit' });
}

function writeEnvFile() {
    // Self-contained: with APP_ENV=e2e, Laravel loads ONLY this file. Drivers are
    // file/array/sync to keep the run hermetic (no extra tables, no worker).
    const appKey = `base64:${randomBytes(32).toString('base64')}`;
    fs.writeFileSync(
        E2E_ENV_FILE,
        `# Generated by tests/e2e/prepare.mjs — throwaway, gitignored, do not edit.
APP_NAME=MelaFreelance
APP_ENV=e2e
APP_KEY=${appKey}
APP_DEBUG=true
APP_URL=${BASE_URL}

# English + euro so text/currency assertions are deterministic.
APP_LOCALE=en
APP_FALLBACK_LOCALE=en
APP_FAKER_LOCALE=en_US
MONEY_CURRENCY=EUR
MONEY_LOCALE=it-IT

# Single-user, exactly like a default self-hosted install.
REGISTRATION_ENABLED=false

# Isolated SQLite; sessions/cache/queue kept out of the DB for a clean run.
DB_CONNECTION=sqlite
DB_DATABASE=${E2E_DATABASE}
SESSION_DRIVER=file
QUEUE_CONNECTION=sync
CACHE_STORE=array
MAIL_MAILER=log

# Fast, cheap password hashing for the throwaway owner account.
BCRYPT_ROUNDS=4

LOG_CHANNEL=stack
LOG_LEVEL=debug
`,
    );
}

function ensureFrontendBuilt() {
    // app.blade.php preloads page components via @vite; without a build the pages
    // 500 with "Unable to locate file in Vite manifest". Reuse an existing build
    // (dev keeps one around); only build when there isn't one.
    const buildDir = path.join(root, 'public', 'build');
    if (fs.existsSync(buildDir) && fs.readdirSync(buildDir).length > 0) {
        return;
    }
    console.log('[e2e] no frontend build found — running `npm run build`…');
    execFileSync('npm', ['run', 'build'], { cwd: root, env: childEnv, stdio: 'inherit' });
}

export function prepare() {
    console.log('[e2e] preparing isolated environment (.env.e2e + fresh SQLite)…');
    writeEnvFile();
    fs.rmSync(E2E_DATABASE, { force: true });
    fs.writeFileSync(E2E_DATABASE, '');
    // Bust any cached config so our env overrides are read at runtime.
    artisan(['config:clear']);
    artisan(['migrate', '--force']);
    artisan(['app:create-user', `--name=${OWNER.name}`, `--email=${OWNER.email}`, `--password=${OWNER.password}`]);
    ensureFrontendBuilt();
    console.log('[e2e] environment ready.');
}

// Run prepare() only when executed directly (the webServer command); a plain
// import (config/specs reading the constants) has no side effects.
if (import.meta.url === pathToFileURL(process.argv[1]).href) {
    prepare();
}
